language: php

sudo: false

dist: trusty

env:
    globals:
        - deps=no

matrix:
    include:
        - php: 5.6
          env: deps=low
        - php: 7.1
    fast_finish: true

#cache:
#  directories:
#    - $HOME/.composer/cache/files

notifications:
  email:
    on_success: change
    on_failure: always

before_install:
  - composer self-update
  - composer clear-cache

install:
#  - composer install --prefer-dist
#  - composer install -n

before_script:
- cd php/
#  - composer install --prefer-dist
#  - composer dump-autoload -o
#  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "5.3" ]]; then composer global require --dev phpunit/phpunit ^4; fi
#  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "5.6" ]]; then composer global require --dev phpunit/phpunit ^5; fi
#  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.1" ]]; then composer global require --dev phpunit/phpunit ^6; fi
#  - composer install --prefer-dist
- if [ "$deps" = "low" ]; then composer --prefer-lowest --prefer-stable update; fi;
- if [ "$deps" = "no" ]; then composer install; fi;
- ls -la
- ls -la vendor/
- cp config-test.php config.php
#  - cd ../

script:
#  - phpunit -d zend.enable_gc=0 --coverage-text
#  - phpunit --coverage-text --verbose --debug
#  - ./vendor/bin/phpunit --coverage-text --verbose --debug
#  - phpunit --coverage-text --verbose --debug
  - php vendor/bin/phpunit  --coverage-text --verbose --debug
#  - pwd
#  - ls -la
#script: phpunit -d zend.enable_gc=0 --verbose --debug

notifications:
  irc: "irc.freenode.org#softhaus"

