language: php
sudo: false
php:
#  - 5.3
  - 5.3
      dist: precise
  - 5.4
  - 5.6
  - 7.0
#  - 5.6
  - 7.1.11
  - nightly
cache:
  directories:
    - $HOME/.composer/cache/files
notifications:
  email:
    on_success: change
    on_failure: always
before_script:
  - cd php/
  - composer install --prefer-dist
#  - composer dump-autoload -o
  - cp config-test.php config.php
#  - cd ../
script:
#  - phpunit -d zend.enable_gc=0 --coverage-text
#  - phpunit --coverage-text --verbose --debug
#  - ./vendor/bin/phpunit --coverage-text --verbose --debug
  - ./vendor/bin/phpunit --coverage-text
#  - pwd
#  - ls -la
#script: phpunit -d zend.enable_gc=0 --verbose --debug
