language: php
sudo: false
dist: trusty
php:
#  - 5.3
  - 5.6
  - 7.1.11
  - nightly
cache:
  directories:
    - $HOME/.composer/cache/files
notifications:
  email:
    on_success: change
    on_failure: always
before_script:
  - cd php/
#  - composer install --prefer-dist
#  - composer dump-autoload -o
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "5.3" ]]; then composer global require --dev phpunit/phpunit ^4; fi
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "5.6" ]]; then composer global require --dev phpunit/phpunit ^5; fi
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.1" ]]; then composer global require --dev phpunit/phpunit ^6; fi
  - cp config-test.php config.php
#  - cd ../
script:
#  - phpunit -d zend.enable_gc=0 --coverage-text
#  - phpunit --coverage-text --verbose --debug
#  - ./vendor/bin/phpunit --coverage-text --verbose --debug
  - ./vendor/bin/phpunit --coverage-text
#  - pwd
#  - ls -la
#script: phpunit -d zend.enable_gc=0 --verbose --debug
